spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cinema
    username: postgres
    password: postgres
    driver: org.postgresql.Driver
app:
  site-api: https://localhost:8080/cinema/api
  admin_token: "user-token"
  admin_password: "secretadmin123"